# Hide sensitive information from log
no_log_value: true

os_env_umask: "022"
os_filesystem_whitelist:
  - vfat
ssh_allow_tcp_forwarding: "yes"
ssh_max_auth_retries: 10
ssh_host_key_algorithms:
  - '+ssh-rsa'
sshd_custom_options:
  - 'PubkeyAcceptedKeyTypes +ssh-rsa'
ssh_server_match_user:
  - user: 'grandmotivator'
    rules:
      - 'AllowAgentForwarding yes'

common_ip_whitelist:
  - "127.0.0.1"

additional_ip_whitelist: []

public_ports:
  - 80
  - 443

common_users:
  - name: "grandmotivator"
    password: "{{ lookup('ansible.builtin.file', '/srv/user-passwords.txt') }}"
    ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1DhhHPprFDVQ7q2w7aJZcZ8fLArzNffhwybeDGU9vOW/QIxDFmz0FQc0nJ7BhQSYcT6o0n/3RmH0aPvJptmFY2/ttldu6y3F5SXEp68TwCBJ+e1tIaP9PYwyuBwSPwxssT0UX6Bv2nY6lbl6ExuKmrRajKg+UB9RRTO61IQnz0ME+rsHBVdqiNoX8j3tv2jUK/RKU7y2IQKySTtdNuThu67vC7SD61GEURSKa3YZWWpwwVR+1hRtdApoyUuR0Ek8Lx0AWlFTd+CPu71vT7ZHx8oeDq6Pil8TxvY+TmTd6l8Kbb9MYkFPI+QHmQLp2Dm88RJzOoB1RDGMMpQq/GqJf0w+6a3exnbM4rnMcTHKg+IlPxpYS9Qy7Yo1Lq+QekSup88btezD+BkSF+u4MyU4lgQsM+Nm1E1k4IOJ3A5HYxnuxJVL5OCiMHzAaqHFsO2qK7Ds2b0UKaBie8QmAMSbsbRs8Q5sIKsEugVFPqDLZUqsGXmmGAe7ubpAieMCWnD/LSntETSko+J6zLYYEDZyhbwLMnJJV+0my3c3CCMBMIwSOe51rgbQ3HYjn8htcFouTTmLD6Ksk8UDoq4Hxzm0sLJN4TwpEKFvdyuITAyPTTOy2u43Na4VbJ8zrBBtlWqKjWqCQ1WjQUa2cazk2d/W4O7hZtJXafnjCoSL0pVh1Uw== grandmotivator"

revoked_users: []

swap_file_size_mb: '4096'
swap_swappiness: '0'

php_default_version_debian: "7.4"
php_webserver_daemon: nginx
php_enable_webserver: true
php_install_recommends: false
php_enable_apc: false
php_enable_php_fpm: true
php_expose_php: "Off"
php_sendmail_path: /usr/sbin/exim4 -t
php_post_max_size: "210M"
php_upload_max_filesize: "200M"
php_max_execution_time: "360"
php_max_input_time: "360"
php_memory_limit: "4096M"
php_date_timezone: "UTC"
php_disable_functions:
  - pcntl_alarm
  - pcntl_fork
  - pcntl_wait

nginx_worker_connections: 1024
nginx_server_tokens: "off"
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_client_max_body_size: "40m"
nginx_keepalive_timeout: 15
nginx_extra_http_options: |
  open_file_cache max=1000 inactive=20s;
  open_file_cache_valid 30s;
  open_file_cache_min_uses 5;
  open_file_cache_errors off;
  types_hash_max_size 2048;
  client_body_buffer_size 10K;
  client_header_buffer_size 1k;
  large_client_header_buffers 2 1k;
  client_body_timeout 12;
  client_header_timeout 12;
  send_timeout 10;
  proxy_read_timeout 7777;
  proxy_connect_timeout 7777;
  gzip on;
  gzip_vary on;
  gzip_disable msie6;
  gzip_types
    text/plain
    text/css
    application/json
    application/x-javascript
    text/xml
    application/xml
    application/xml+rss
    text/javascript
    application/javascript
    image/svg+xml
    image/jpeg;
  gzip_comp_level 5;
  gzip_min_length 800;
  gzip_proxied any;
  expires 1w;


supervisor_inet_http_server_enable: true
