- name: Allow all access to some public tcp ports
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - "{{ public_ports }}"

- name: Allow all access from networks to this host
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  with_items:
    - "{{ common_ip_whitelist }}"
    - "{{ additional_ip_whitelist }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Check if file exist
  ansible.builtin.stat:
    path: "/etc/sshguard/whitelist"
  register: sshguard

- name: Generate whitelist hosts for sshguard
  ansible.builtin.blockinfile:
    dest: /etc/sshguard/whitelist
    block: |
      {% for host in common_ip_whitelist %}
      {{ host }}
      {% endfor %}
      {% for host in additional_ip_whitelist %}
      {{ host }}
      {% endfor %}
  when: sshguard.stat.exists
  notify:
    - Restart sshguard
  tags:
    - firewall
